name: Build Vue
on: [push]
permissions:
  contents: write
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
      - uses: actions/checkout@v2
      - id: Build-Vue
        uses: xRealNeon/VuePagesAction@1.0.1
        with:
          username: 'mihai-dicianu'
          reponame: 'cigarette-fighter'
          token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
